name = "docagent"
main = "src/index.ts" #æ˜ç¡®æŒ‡å‡º main æ¨¡å—ï¼
compatibility_date = "2024-11-06"

[site]
bucket = "./public" # ç¡®è®¤è¿™æ˜¯æ–°å¢çš„publicæ–‡ä»¶å¤¹ï¼Œè·¯å¾„æ­£ç¡®å­˜åœ¨
# ğŸ”¥ å¦‚æœä½¿ç”¨ Workers Sites
[[kv_namespaces]]
binding = "ASSETS"
id = "832b93be1b59476e838a6b8615bbb4d6"
preview_id = "__docagent-workers_sites_assets"

[[d1_databases]]
binding = "D1"
database_name = "whiteboard"
database_id = "4f65e16b-740b-4af0-ac63-2d47f6bb6f77"

[[r2_buckets]]
binding = "R2"
bucket_name = "aiagentppt"